{
	"code": 0,
	"msg": "",
	"count":21,
	"data": [
		{
			"id": 1,
			"pc": "1332244",
			"pcxlh": "Awe23",
			"zdjbh": "173.0.0.1:8088",
			"pclx": "2MTD",			
			"status": "正常",			
			"time": "2018-09-03 15:32",
			"time_":"12:03:35",
			"depart":"教务处",
			"pardepart":"教职工",
			"name":"李晓",
			"status3":"未上传脱机记录",
			"moneyBig":"882",
			"jysc":"2.2s",
			"ycratel":"0.01%",
			"call":"10ms",
			"ylwl":"未领",
			"sm":"未发卡",
			"parmname":"1类卡管理费比例",
			"zdbm":"31",
			"sblx1":"消费工作站90",
			"ssyy":"门禁应用",
			"yhname":"lixiao",
			"cslx":"系统参数",
			"qywjm":"签约001.xls",
			"erdu":"100",
			"signway":"批量签约",
			"yh":"徽商银行",
			"yhkh":"623251856565656882",
			"idsmall":"宿舍管理员",
			"idbig":"校职工",
			"sex":"男",
			"yesno":"是",
			"school":"景泰第一中学",
			"rolenamebz":"出纳员权限",
			"rolename":"出纳员",
			"zixitong":"身份识别系统",
			"caijiname":"工作站1",
			"sbmc":"食堂一层圈存",
			"sblx":"圈存机",
			"jsbmmc":"老校区充值",
			"kmms":"购水支出",
			"kmlx":"终端消费类",
			"mealname":"早餐",
			"money":"150",
			"pctype":"周期补助",
			"shuoming":"已发放",
			"parname":"NSNPCorrect",
			"zwname":"消费机运行参数组",
			"describe":"1类卡管理费比例。填百分比中的分子值。例如：5,表示5%",
			"lei":"1类卡",
			"wlzt":"在线",
			"use":"禁用",
			"ssdl":"身份识别类",
			"cardzt":"已发卡"
			
		},
		{
			"id": 2,
			"pc": "1332244",
			"pcxlh": "Awe23",
			"zdjbh": "172.02.0.1:8086",
			"pclx": "3MTD",			
			"status": "正常",			
			"time": "2018-09-03 15:42",
			"time_":"12:03:35",
			"depart":"食堂1",
			"pardepart":"教职工",
			"name":"李晓",
			"status3":"未上传脱机记录",
			"moneyBig":"122",
			"jysc":"2.2s",
			"ycratel":"0.01%",
			"call":"10ms",
			"ylwl":"已领",
			"sm":"存在交叉补助",
			"parmname":"2类卡管理费比例",
			"zdbm":"33",
			"sblx1":"消费工作站80",
			"ssyy":"考勤应用",
			"yhname":"lixiao",
			"cslx":"系统参数",
			"qywjm":"签约001.xls",
			"erdu":"150",
			"signway":"批量签约",
			"yh":"交通银行",
			"yhkh":"62325154345678788",
			"idsmall":"武警",
			"idbig":"警察",
			"sex":"女",
			"yesno":"否",
			"school":"景泰第一中学",
			"rolenamebz":"管理员权限",
			"rolename":"管理员",
			"zixitong":"身份识别系统",
			"caijiname":"工作站2",
			"sbmc":"网上银行",
			"sblx":"消费机",
			"jsbmmc":"老校区医务室",
			"kmms":"购电支出",
			"kmlx":"终端消费类",
			"mealname":"午餐",
			"money":"0",
			"pctype":"文件补助",
			"shuoming":"已发放",
			"parname":"NSNPCorrect",
			"zwname":"水控运行参数组",
			"describe":"2类卡管理费比例。填百分比中的分子值。例如：5,表示5%",
			"lei":"1类卡",
			"wlzt":"离线",
			"use":"启用",
			"ssdl":"管理费类",
			"cardzt":"未发卡"
			
		},
		{
			"id": 3,
			"pc": "13322441",
			"pcxlh": "A2we23",
			"zdjbh": "173.0.0.1:8088",
			"pclx": "4MTD",			
			"status": "正常",
			"ysl": 100,
			"sysl": 9,
			"fjlx": "学生宿舍1",
			"time": "2018-09-03 15:32",
			"time_":"12:03:35",
			"depart":"食堂12",
			"pardepart":"教职工",
			"name":"李晓",
			"status3":"未上传脱机记录",
			"moneyBig":"600",
			"jysc":"2.2s",
			"ycratel":"0.01%",
			"call":"10ms",
			"ylwl":"未领",
			"sm":"存在交叉补助",
			"parmname":"3类卡管理费比例",
			"zdbm":"34",
			"sblx1":"消费工作站90",
			"ssyy":"消费应用",
			"yhname":"lixiao",
			"cslx":"系统参数",
			"qywjm":"签约001.xls",
			"erdu":"50",
			"signway":"批量签约",
			"yh":"招商银行",
			"yhkh":"62325777765656882",
			"idsmall":"宿舍管理员",
			"idbig":"校职工",
			"sex":"女",
			"yesno":"否",
			"school":"景泰第一中学",
			"rolenamebz":"管理员权限",
			"rolename":"管理员",
			"zixitong":"消费系统",
			"caijiname":"工作站3",
			"sbmc":"食堂二层圈存",
			"sblx":"圈存机",
			"jsbmmc":"老校区充值",
			"kmms":"四六级支出",
			"kmlx":"终端消费类",
			"mealname":"晚餐",
			"money":"150",
			"pctype":"周期补助",
			"shuoming":"已发放",
			"parname":"NSNPCorrect",
			"zwname":"平台运行参数组",
			"describe":"3类卡管理费比例。填百分比中的分子值。例如：5,表示5%",
			"lei":"3类卡",
			"wlzt":"在线",
			"use":"禁用",
			"ssdl":"身份识别类",
			"cardzt":"已发卡"
			
		},
		{
			"id": 4,
			"pc": "13322444",
			"pcxlh": "bwe23",
			"zdjbh": "173.0.0.1:8088",
			"pclx": "2MTD",			
			"status": "正常",			
			"time": "2018-09-03 15:32",
			"time_":"12:03:35",
			"depart":"教务处",
			"pardepart":"教职工",
			"name":"李晓",
			"status3":"未上传脱机记录",
			"moneyBig":"550",
			"jysc":"2.2s",
			"ycratel":"0.01%",
			"call":"10ms",
			"ylwl":"已领",
			"sm":"可补发",
			"parmname":"4类卡管理费比例",
			"zdbm":"35",
			"sblx1":"消费工作站",
			"ssyy":"门禁应用",
			"yhname":"lixiao",
			"cslx":"系统参数",
			"qywjm":"签约001.xls",
			"erdu":"100",
			"signway":"批量签约",
			"yh":"农业银行",
			"yhkh":"62325185657777882",
			"idsmall":"宿舍管理员",
			"idbig":"校职工",
			"sex":"女",
			"yesno":"否",
			"school":"景泰第一中学",
			"rolenamebz":"出纳员权限",
			"rolename":"出纳员",
			"zixitong":"身份识别系统",
			"caijiname":"工作站4",
			"sbmc":"网上银行",
			"sblx":"圈存机",
			"jsbmmc":"虚拟业务部门",
			"kmms":"洗衣支出",
			"kmlx":"终端消费类",
			"mealname":"早餐",
			"money":"150",
			"pctype":"文件补助",
			"shuoming":"已发放",
			"parname":"NSNPCorrect",
			"zwname":"消费机运行参数组",
			"describe":"4类卡管理费比例。填百分比中的分子值。例如：5,表示5%",
			"lei":"1类卡",
			"wlzt":"在线",
			"use":"禁用",
			"ssdl":"身份识别类",
			"cardzt":"未发卡"
			
		},
		{
			"id": 5,
			"pc": "13322445",
			"pcxlh": "Cwe23",
			"zdjbh": "172.215.0.123:8080",
			"pclx": "2MTD",			
			"status": "正常",			
			"time": "2018-09-03 15:32",
			"time_":"12:03:35",
			"depart":"水控1",
			"pardepart":"教职工",
			"name":"李晓",
			"status3":"未上传脱机记录",
			"moneyBig":"300",
			"jysc":"2.2s",
			"ycratel":"0.01%",
			"call":"10ms",
			"ylwl":"已领",
			"sm":"未发卡",
			"parmname":"5类卡管理费比例",
			"zdbm":"36",
			"sblx1":"消费工作站",
			"ssyy":"消费应用",
			"yhname":"lixiao",
			"cslx":"系统参数",
			"qywjm":"签约001.xls",
			"erdu":"200",
			"signway":"批量签约",
			"yh":"徽商银行",
			"yhkh":"623251856565656882",
			"idsmall":"小学生",
			"idbig":"学生",
			"sex":"男",
			"yesno":"是",
			"school":"景泰第一中学",
			"rolenamebz":"管理员权限",
			"rolename":"管理员",
			"zixitong":"消费系统",
			"caijiname":"工作站5",
			"sbmc":"超市圈存",
			"sblx":"消费机",
			"jsbmmc":"医专老区食堂",
			"kmms":"购电支出",
			"kmlx":"终端消费类",
			"mealname":"午餐",
			"money":"150",
			"pctype":"周期补助",
			"shuoming":"已发放",
			"parname":"NSNPCorrect",
			"zwname":"卡务中心运行参数组",
			"describe":"5类卡管理费比例。填百分比中的分子值。例如：5,表示5%",
			"lei":"1类卡",
			"wlzt":"离线",
			"use":"启用",
			"ssdl":"身份识别类",
			"cardzt":"已发卡"
			
		},
		{
			"id": 6,
			"pc": "1332244",
			"pcxlh": "Dwe23",
			"zdjbh": "172.215.0.123:8080",
			"pclx": "2MTD",			
			"status": "正常",			
			"time": "2018-09-03 15:32",
			"time_":"12:03:35",
			"depart":"教务处",
			"pardepart":"教职工",
			"name":"李晓",
			"status3":"未上传脱机记录",
			"moneyBig":"882",
			"jysc":"2.2s",
			"ycratel":"0.01%",
			"call":"10ms",
			"ylwl":"已领",
			"sm":"存在交叉补助",
			"parmname":"6类卡管理费比例",
			"zdbm":"40",
			"sblx1":"消费工作站90",
			"ssyy":"消费应用",
			"yhname":"lixiao",
			"cslx":"系统参数",
			"qywjm":"签约001.xls",
			"erdu":"300",
			"signway":"批量签约",
			"yh":"徽商银行",
			"yhkh":"623251856565656882",
			"idsmall":"宿舍管理员",
			"idbig":"校职工",
			"sex":"女",
			"yesno":"否",
			"school":"景泰第一中学",
			"rolenamebz":"出纳员权限",
			"rolename":"出纳员",
			"zixitong":"消费系统",
			"caijiname":"工作站1",
			"sbmc":"医务室圈存",
			"sblx":"消费机",
			"jsbmmc":"医专老区超市",
			"kmms":"购水支出",
			"kmlx":"终端消费类",
			"mealname":"早餐",
			"money":"150",
			"pctype":"文件补助",
			"shuoming":"已发放",
			"parname":"NSNPCorrect",
			"zwname":"消费机运行参数组",
			"describe":"6类卡管理费比例。填百分比中的分子值。例如：5,表示5%",
			"lei":"3类卡",
			"wlzt":"在线",
			"use":"禁用",
			"ssdl":"管理费类",
			"cardzt":"未发卡"
			
		},
		{
			"id": 7,
			"pc": "1332244",
			"pcxlh": "Ewe23",
			"zdjbh": "172.215.0.123:8080",
			"pclx": "2MTD",			
			"status": "正常",			
			"time": "2018-09-03 15:32",
			"time_":"12:03:35",
			"depart":"教务处",
			"pardepart":"教职工",
			"name":"李晓",
			"status3":"未上传脱机记录",
			"moneyBig":"50",
			"jysc":"2.2s",
			"ycratel":"0.01%",
			"call":"10ms",
			"ylwl":"未领",
			"sm":"未发卡",
			"parmname":"7类卡管理费比例",
			"zdbm":"42",
			"sblx1":"消费工作站90",
			"ssyy":"消费应用",
			"yhname":"lixiao",
			"cslx":"系统参数",
			"qywjm":"签约001.xls",
			"erdu":"350",
			"signway":"批量签约",
			"yh":"徽商银行",
			"yhkh":"623251856565656882",
			"idsmall":"大学老师",
			"idbig":"老师",
			"sex":"男",
			"yesno":"是",
			"school":"景泰第一中学",
			"rolenamebz":"管理员权限",
			"rolename":"管理员",
			"zixitong":"消费系统",
			"caijiname":"工作站2",
			"sbmc":"食堂一层圈存",
			"sblx":"消费机",
			"jsbmmc":"医专老区食堂",
			"kmms":"购水支出",
			"kmlx":"终端消费类",
			"mealname":"晚餐",
			"money":"150",
			"pctype":"周期补助",
			"shuoming":"已发放",
			"parname":"NSNPCorrect",
			"zwname":"卡务中心运行参数组",
			"describe":"7类卡管理费比例。填百分比中的分子值。例如：5,表示5%",
			"lei":"1类卡",
			"wlzt":"在线",
			"use":"启用",
			"ssdl":"管理费类",
			"cardzt":"已发卡"
			
		},
		{
			"id": 8,
			"pc": "13322448",
			"pcxlh": "fwe23",
			"zdjbh": "172.215.0.123:8080",
			"pclx": "2MTD",			
			"status": "正常",			
			"time": "2018-09-03 15:32",
			"time_":"12:03:35",
			"depart":"教务处",
			"pardepart":"教职工",
			"name":"李晓",
			"status3":"未上传脱机记录",
			"moneyBig":"125",
			"jysc":"2.2s",
			"ycratel":"0.01%",
			"call":"10ms",
			"ylwl":"已领",
			"sm":"存在交叉补助",
			"parmname":"8类卡管理费比例",
			"zdbm":"43",
			"sblx1":"消费工作站",
			"ssyy":"消费应用",
			"yhname":"lixiao",
			"cslx":"系统参数",
			"qywjm":"签约001.xls",
			"erdu":"500",
			"signway":"批量签约",
			"yh":"徽商银行",
			"yhkh":"623251856565656882",
			"idsmall":"宿舍管理员",
			"idbig":"校职工",
			"sex":"女",
			"yesno":"是",
			"school":"景泰第一中学",
			"rolenamebz":"出纳员权限",
			"rolename":"出纳员",
			"zixitong":"消费系统",
			"caijiname":"工作站3",
			"sbmc":"食堂一层圈存",
			"sblx":"圈存机",
			"jsbmmc":"老校区充值",
			"kmms":"购水支出",
			"kmlx":"终端消费类",
			"mealname":"宵夜",
			"money":"150",
			"pctype":"文件补助",
			"shuoming":"已发放",
			"parname":"NSNPCorrect",
			"zwname":"消费机运行参数组",
			"describe":"8类卡管理费比例。填百分比中的分子值。例如：5,表示5%",
			"lei":"1类卡",
			"wlzt":"离线",
			"use":"启用",
			"ssdl":"管理费类",
			"cardzt":"未发卡"
			
		},
		{
			"id": 9,
			"pc": "1332244",
			"pcxlh": "Gwe23",
			"zdjbh": "172.215.0.123:8080",
			"pclx": "2MTD",			
			"status": "正常",			
			"time": "2018-09-03 15:32",
			"time_":"12:03:35",
			"depart":"教务处",
			"pardepart":"教职工",
			"name":"李晓",
			"status3":"未上传脱机记录",
			"moneyBig":"882",
			"jysc":"2.2s",
			"ycratel":"0.01%",
			"call":"10ms",
			"ylwl":"已领",
			"sm":"未发卡",
			"parmname":"9类卡管理费比例",
			"zdbm":"44",
			"sblx1":"消费工作站",
			"ssyy":"消费应用",
			"yhname":"lixiao",
			"cslx":"系统参数",
			"qywjm":"签约001.xls",
			"erdu":"600",
			"signway":"批量签约",
			"yh":"徽商银行",
			"yhkh":"623251856565656882",
			"idsmall":"宿舍管理员",
			"idbig":"校职工",
			"sex":"男",
			"yesno":"是",
			"school":"景泰第一中学",
			"rolenamebz":"出纳员权限",
			"rolename":"出纳员",
			"zixitong":"消费系统",
			"caijiname":"工作站1",
			"sbmc":"食堂一层圈存",
			"sblx":"圈存机",
			"jsbmmc":"老校区充值",
			"kmms":"购水支出",
			"kmlx":"终端消费类",
			"mealname":"早餐",
			"money":"150",
			"pctype":"周期补助",
			"shuoming":"已发放",
			"parname":"NSNPCorrect",
			"zwname":"平台运行参数组",
			"describe":"9类卡管理费比例。填百分比中的分子值。例如：5,表示5%",
			"lei":"3类卡",
			"wlzt":"在线",
			"use":"启用",
			"ssdl":"管理费类",
			"cardzt":"已发卡"
			
		},
		{
			"id": 10,
			"pc": "1332244",
			"pcxlh": "Hwe23",
			"zdjbh": "172.02.0.1:8086",
			"pclx": "3MTD",			
			"status": "正常",			
			"time": "2018-09-03 15:42",
			"time_":"12:03:35",
			"depart":"教务处",
			"pardepart":"教职工",
			"name":"李晓",
			"status3":"未上传脱机记录",
			"moneyBig":"882",
			"jysc":"2.2s",
			"ycratel":"0.01%",
			"call":"10ms",
			"ylwl":"已领",
			"sm":"未发卡",
			"parmname":"1类卡管理费比例",
			"zdbm":"45",
			"sblx1":"消费工作站90",
			"ssyy":"消费应用",
			"yhname":"lixiao",
			"cslx":"系统参数",
			"qywjm":"签约001.xls",
			"erdu":"230",
			"signway":"批量签约",
			"yh":"徽商银行",
			"yhkh":"623251856565656882",
			"idsmall":"宿舍管理员",
			"idbig":"校职工",
			"sex":"男",
			"yesno":"是",
			"school":"景泰第一中学",
			"rolenamebz":"出纳员权限",
			"rolename":"出纳员",
			"zixitong":"消费系统",
			"caijiname":"工作站1",
			"sbmc":"食堂一层圈存",
			"sblx":"圈存机",
			"jsbmmc":"老校区充值",
			"kmms":"购水支出",
			"kmlx":"终端消费类",
			"mealname":"早餐",
			"money":"150",
			"pctype":"文件补助",
			"shuoming":"已发放",
			"parname":"NSNPCorrect",
			"zwname":"平台运行参数组",
			"describe":"1类卡管理费比例。填百分比中的分子值。例如：5,表示5%",
			"lei":"1类卡",
			"wlzt":"在线",
			"use":"启用",
			"ssdl":"身份识别类",
			"cardzt":"未发卡"
			
		},
		{
			"id": 11,
			"pc": "13322441",
			"pcxlh": "IIwe23",
			"zdjbh": "173.0.0.1:8088",
			"pclx": "4MTD",			
			"status": "正常",
			"ysl": 100,
			"sysl": 9,
			"fjlx": "学生宿舍1",
			"time": "2018-09-03 15:32",
			"time_":"12:03:35",
			"depart":"教务处",
			"pardepart":"教职工",
			"name":"李晓",
			"status3":"未上传脱机记录",
			"moneyBig":"882",
			"jysc":"2.2s",
			"ycratel":"0.01%",
			"call":"10ms",
			"ylwl":"已领",
			"sm":"未发卡",
			"parmname":"1类卡管理费比例",
			"zdbm":"46",
			"sblx1":"消费工作站90",
			"ssyy":"消费应用",
			"yhname":"lixiao",
			"cslx":"系统参数",
			"qywjm":"签约001.xls",
			"erdu":"111",
			"signway":"批量签约",
			"yh":"徽商银行",
			"yhkh":"623251856565656882",
			"idsmall":"保安",
			"idbig":"校职工",
			"sex":"男",
			"yesno":"是",
			"school":"景泰第一中学",
			"rolenamebz":"出纳员权限",
			"rolename":"出纳员",
			"zixitong":"消费系统",
			"caijiname":"工作站1",
			"sbmc":"食堂一层圈存",
			"sblx":"圈存机",
			"jsbmmc":"老校区充值",
			"kmms":"购水支出",
			"kmlx":"终端消费类",
			"mealname":"早餐",
			"money":"150",
			"pctype":"周期补助",
			"shuoming":"已发放",
			"parname":"NSNPCorrect",
			"zwname":"消费机运行参数组",
			"describe":"1类卡管理费比例。填百分比中的分子值。例如：5,表示5%",
			"lei":"1类卡",
			"wlzt":"离线",
			"use":"启用",
			"ssdl":"其他",
			"cardzt":"已发卡"
			
		},
		{
			"id": 12,
			"pc": "13322444",
			"pcxlh": "Jwe23",
			"zdjbh": "172.215.0.123:8080",
			"pclx": "2MTD",			
			"status": "正常",			
			"time": "2018-09-03 15:32",
			"time_":"12:03:35",
			"depart":"教务处",
			"pardepart":"教职工",
			"name":"李晓",
			"status3":"未上传脱机记录",
			"moneyBig":"882",
			"jysc":"2.2s",
			"ycratel":"0.01%",
			"call":"10ms",
			"ylwl":"已领",
			"sm":"未发卡",
			"parmname":"1类卡管理费比例",
			"zdbm":"47",
			"sblx1":"消费工作站90",
			"ssyy":"消费应用",
			"yhname":"lixiao",
			"cslx":"系统参数",
			"qywjm":"签约001.xls",
			"erdu":"65",
			"signway":"批量签约",
			"yh":"徽商银行",
			"yhkh":"623251856565656882",
			"idsmall":"食堂柜员",
			"idbig":"校职工",
			"sex":"男",
			"yesno":"是",
			"school":"景泰第一中学",
			"rolenamebz":"出纳员权限",
			"rolename":"出纳员",
			"zixitong":"消费系统",
			"caijiname":"工作站1",
			"sbmc":"食堂一层圈存",
			"sblx":"圈存机",
			"jsbmmc":"老校区充值",
			"kmms":"购水支出",
			"kmlx":"终端消费类",
			"mealname":"早餐",
			"money":"150",
			"pctype":"文件补助",
			"shuoming":"已发放",
			"parname":"NSNPCorrect",
			"zwname":"消费机运行参数组",
			"describe":"1类卡管理费比例。填百分比中的分子值。例如：5,表示5%",
			"lei":"3类卡",
			"wlzt":"在线",
			"use":"启用",
			"ssdl":"其他",
			"cardzt":"未发卡"
			
		},
		{
			"id": 13,
			"pc": "13322445",
			"pcxlh": "Kwe23",
			"zdjbh": "172.215.0.123:8080",
			"pclx": "2MTD",			
			"status": "正常",			
			"time": "2018-09-03 15:32",
			"time_":"12:03:35",
			"depart":"教务处",
			"pardepart":"教职工",
			"name":"李晓",
			"status3":"未上传脱机记录",
			"moneyBig":"882",
			"jysc":"2.2s",
			"ycratel":"0.01%",
			"call":"10ms",
			"ylwl":"已领",
			"sm":"未发卡",
			"parmname":"1类卡管理费比例",
			"zdbm":"48",
			"sblx1":"消费工作站90",
			"ssyy":"消费应用",
			"yhname":"lixiao",
			"cslx":"系统参数",
			"qywjm":"签约001.xls",
			"erdu":"100",
			"signway":"批量签约",
			"yh":"徽商银行",
			"yhkh":"623251856565656882",
			"idsmall":"宿舍管理员",
			"idbig":"校职工",
			"sex":"男",
			"yesno":"是",
			"school":"景泰第一中学",
			"rolenamebz":"出纳员权限",
			"rolename":"出纳员",
			"zixitong":"消费系统",
			"caijiname":"工作站1",
			"sbmc":"食堂一层圈存",
			"sblx":"圈存机",
			"jsbmmc":"老校区充值",
			"kmms":"购水支出",
			"kmlx":"终端消费类",
			"mealname":"早餐",
			"money":"150",
			"pctype":"周期补助",
			"shuoming":"已发放",
			"parname":"NSNPCorrect",
			"zwname":"消费机运行参数组",
			"describe":"1类卡管理费比例。填百分比中的分子值。例如：5,表示5%",
			"lei":"1类卡",
			"wlzt":"在线",
			"use":"启用",
			"ssdl":"其他",
			"cardzt":"已发卡"
			
		},
		{
			"id": 14,
			"pc": "1332244",
			"pcxlh": "Lwe23",
			"zdjbh": "172.215.0.123:8080",
			"pclx": "2MTD",			
			"status": "正常",			
			"time": "2018-09-03 15:32",
			"time_":"12:03:35",
			"depart":"教务处",
			"pardepart":"教职工",
			"name":"李晓",
			"status3":"未上传脱机记录",
			"moneyBig":"882",
			"jysc":"2.2s",
			"ycratel":"0.01%",
			"call":"10ms",
			"ylwl":"已领",
			"sm":"未发卡",
			"parmname":"1类卡管理费比例",
			"zdbm":"49",
			"sblx1":"消费工作站90",
			"ssyy":"消费应用",
			"yhname":"lixiao",
			"cslx":"系统参数",
			"qywjm":"签约001.xls",
			"erdu":"100",
			"signway":"批量签约",
			"yh":"徽商银行",
			"yhkh":"623251856565656882",
			"idsmall":"保安",
			"idbig":"校职工",
			"sex":"男",
			"yesno":"是",
			"school":"景泰第一中学",
			"rolenamebz":"出纳员权限",
			"rolename":"出纳员",
			"zixitong":"消费系统",
			"caijiname":"工作站1",
			"sbmc":"食堂一层圈存",
			"sblx":"圈存机",
			"jsbmmc":"老校区充值",
			"kmms":"购水支出",
			"kmlx":"终端消费类",
			"mealname":"早餐",
			"money":"150",
			"pctype":"文件补助",
			"shuoming":"已发放",
			"parname":"NSNPCorrect",
			"zwname":"消费机运行参数组",
			"describe":"1类卡管理费比例。填百分比中的分子值。例如：5,表示5%",
			"lei":"1类卡",
			"wlzt":"离线",
			"use":"启用",
			"ssdl":"其他",
			"cardzt":"未发卡"
			
		},
		{
			"id": 15,
			"pc": "1332244",
			"pcxlh": "Mwe23",
			"zdjbh": "172.215.0.123:8080",
			"pclx": "2MTD",			
			"status": "正常",			
			"time": "2018-09-03 15:32",
			"time_":"12:03:35",
			"depart":"教务处",
			"pardepart":"教职工",
			"name":"李晓",
			"status3":"未上传脱机记录",
			"moneyBig":"882",
			"jysc":"2.2s",
			"ycratel":"0.01%",
			"call":"10ms",
			"ylwl":"已领",
			"sm":"未发卡",
			"parmname":"1类卡管理费比例",
			"zdbm":"50",
			"sblx1":"消费工作站90",
			"ssyy":"消费应用",
			"yhname":"lixiao",
			"cslx":"系统参数",
			"qywjm":"签约001.xls",
			"erdu":"100",
			"signway":"批量签约",
			"yh":"徽商银行",
			"yhkh":"623251856565656882",
			"idsmall":"宿舍管理员",
			"idbig":"校职工",
			"sex":"男",
			"yesno":"是",
			"school":"景泰第一中学",
			"rolenamebz":"出纳员权限",
			"rolename":"出纳员",
			"zixitong":"消费系统",
			"caijiname":"工作站1",
			"sbmc":"食堂一层圈存",
			"sblx":"圈存机",
			"jsbmmc":"老校区充值",
			"kmms":"购水支出",
			"kmlx":"终端消费类",
			"mealname":"早餐",
			"money":"150",
			"pctype":"周期补助",
			"shuoming":"已发放",
			"parname":"NSNPCorrect",
			"zwname":"消费机运行参数组",
			"describe":"1类卡管理费比例。填百分比中的分子值。例如：5,表示5%",
			"lei":"3类卡",
			"wlzt":"在线",
			"use":"启用",
			"ssdl":"其他",
			"cardzt":"已发卡"
			
		},
		{
			"id": 16,
			"pc": "13322448",
			"pcxlh": "Nwe23",
			"zdjbh": "172.215.0.123:8080",
			"pclx": "2MTD",			
			"status": "正常",			
			"time": "2018-09-03 15:32",
			"time_":"12:03:35",
			"depart":"教务处",
			"pardepart":"教职工",
			"name":"李晓",
			"status3":"未上传脱机记录",
			"moneyBig":"882",
			"jysc":"2.2s",
			"ycratel":"0.01%",
			"call":"10ms",
			"ylwl":"已领",
			"sm":"未发卡",
			"parmname":"1类卡管理费比例",
			"zdbm":"30",
			"sblx1":"消费工作站90",
			"ssyy":"消费应用",
			"yhname":"lixiao",
			"cslx":"系统参数",
			"qywjm":"签约001.xls",
			"erdu":"100",
			"signway":"批量签约",
			"yh":"徽商银行",
			"yhkh":"623251856565656882",
			"idsmall":"宿舍管理员",
			"idbig":"校职工",
			"sex":"男",
			"yesno":"是",
			"school":"景泰第一中学",
			"rolenamebz":"出纳员权限",
			"rolename":"出纳员",
			"zixitong":"消费系统",
			"caijiname":"工作站1",
			"sbmc":"食堂一层圈存",
			"sblx":"圈存机",
			"jsbmmc":"老校区充值",
			"kmms":"购水支出",
			"kmlx":"终端消费类",
			"mealname":"早餐",
			"money":"150",
			"pctype":"文件补助",
			"shuoming":"已发放",
			"parname":"NSNPCorrect",
			"zwname":"消费机运行参数组",
			"describe":"1类卡管理费比例。填百分比中的分子值。例如：5,表示5%",
			"lei":"1类卡",
			"wlzt":"在线",
			"use":"启用",
			"ssdl":"其他",
			"cardzt":"未发卡"
			
		},
		{
			"id": 17,
			"pc": "1332244",
			"pcxlh": "L222we23",
			"zdjbh": "172.215.0.123:8080",
			"pclx": "2MTD",			
			"status": "正常",			
			"time": "2018-09-03 15:32",
			"time_":"12:03:35",
			"depart":"教务处",
			"pardepart":"教职工",
			"name":"李晓",
			"status3":"未上传脱机记录",
			"moneyBig":"882",
			"jysc":"2.2s",
			"ycratel":"0.01%",
			"call":"10ms",
			"ylwl":"已领",
			"sm":"未发卡",
			"parmname":"1类卡管理费比例",
			"zdbm":"30",
			"sblx1":"消费工作站90",
			"ssyy":"消费应用",
			"yhname":"lixiao",
			"cslx":"系统参数",
			"qywjm":"签约001.xls",
			"erdu":"100",
			"signway":"批量签约",
			"yh":"徽商银行",
			"yhkh":"623251856565656882",
			"idsmall":"宿舍管理员",
			"idbig":"校职工",
			"sex":"男",
			"yesno":"是",
			"school":"景泰第一中学",
			"rolenamebz":"出纳员权限",
			"rolename":"出纳员",
			"zixitong":"消费系统",
			"caijiname":"工作站1",
			"sbmc":"食堂一层圈存",
			"sblx":"圈存机",
			"jsbmmc":"老校区充值",
			"kmms":"购水支出",
			"kmlx":"终端消费类",
			"mealname":"早餐",
			"money":"150",
			"pctype":"周期补助",
			"shuoming":"已发放",
			"parname":"NSNPCorrect",
			"zwname":"消费机运行参数组",
			"describe":"1类卡管理费比例。填百分比中的分子值。例如：5,表示5%",
			"lei":"1类卡",
			"wlzt":"离线",
			"use":"启用",
			"ssdl":"其他",
			"cardzt":"已发卡"
			
		},
		{
			"id": 18,
			"pc": "1332244",
			"pcxlh": "22Mwe23",
			"zdjbh": "172.215.0.123:8080",
			"pclx": "2MTD",			
			"status": "正常",			
			"time": "2018-09-03 15:32",
			"time_":"12:03:35",
			"depart":"教务处",
			"pardepart":"教职工",
			"name":"李晓",
			"status3":"未上传脱机记录",
			"moneyBig":"882",
			"jysc":"2.2s",
			"ycratel":"0.01%",
			"call":"10ms",
			"ylwl":"已领",
			"sm":"未发卡",
			"parmname":"1类卡管理费比例",
			"zdbm":"30",
			"sblx1":"消费工作站90",
			"ssyy":"消费应用",
			"yhname":"lixiao",
			"cslx":"系统参数",
			"qywjm":"签约001.xls",
			"erdu":"100",
			"signway":"批量签约",
			"yh":"徽商银行",
			"yhkh":"623251856565656882",
			"idsmall":"宿舍管理员",
			"idbig":"校职工",
			"sex":"男",
			"yesno":"是",
			"school":"景泰第一中学",
			"rolenamebz":"出纳员权限",
			"rolename":"出纳员",
			"zixitong":"消费系统",
			"caijiname":"工作站1",
			"sbmc":"食堂一层圈存",
			"sblx":"圈存机",
			"jsbmmc":"老校区充值",
			"kmms":"购水支出",
			"kmlx":"终端消费类",
			"mealname":"早餐",
			"money":"150",
			"pctype":"文件补助",
			"shuoming":"已发放",
			"parname":"NSNPCorrect",
			"zwname":"消费机运行参数组",
			"describe":"1类卡管理费比例。填百分比中的分子值。例如：5,表示5%",
			"lei":"3类卡",
			"wlzt":"在线",
			"use":"启用",
			"ssdl":"其他",
			"cardzt":"已发卡"
			
		},
		{
			"id": 19,
			"pc": "13322448",
			"pcxlh": "N3we23",
			"zdjbh": "172.215.0.123:8080",
			"pclx": "2MTD",			
			"status": "正常",			
			"time": "2018-09-03 15:32",
			"time_":"12:03:35",
			"depart":"教务处",
			"pardepart":"教职工",
			"name":"李晓",
			"status3":"未上传脱机记录",
			"moneyBig":"882",
			"jysc":"2.2s",
			"ycratel":"0.01%",
			"call":"10ms",
			"ylwl":"未领",
			"sm":"未发卡",
			"parmname":"1类卡管理费比例",
			"zdbm":"30",
			"sblx1":"消费工作站90",
			"ssyy":"消费应用",
			"yhname":"lixiao",
			"cslx":"系统参数",
			"qywjm":"签约001.xls",
			"erdu":"100",
			"signway":"批量签约",
			"yh":"徽商银行",
			"yhkh":"623251856565656882",
			"idsmall":"宿舍管理员",
			"idbig":"校职工",
			"sex":"男",
			"yesno":"是",
			"school":"景泰第一中学",
			"rolenamebz":"出纳员权限",
			"rolename":"出纳员",
			"zixitong":"消费系统",
			"caijiname":"工作站1",
			"sbmc":"食堂一层圈存",
			"sblx":"圈存机",
			"jsbmmc":"老校区充值",
			"kmms":"购水支出",
			"kmlx":"终端消费类",
			"mealname":"早餐",
			"money":"150",
			"pctype":"周期补助",
			"shuoming":"已发放",
			"parname":"NSNPCorrect",
			"zwname":"消费机运行参数组",
			"describe":"1类卡管理费比例。填百分比中的分子值。例如：5,表示5%",
			"lei":"1类卡",
			"wlzt":"在线",
			"use":"启用",
			"ssdl":"其他",
			"cardzt":"已发卡"
			
		}
	]
}